---
language: python
matrix:
  include:
    - python: 2.7
      dist: trusty
    - python: 3.3
      dist: trusty
    - python: 3.4
      dist: trusty
    - python: 3.5
      dist: trusty
    - python: 3.6
      dist: trusty
    - python: 3.7
      dist: xenial
      env:
        - RUN_SNYK=1
        - RUN_LINTER=1
    - python: nightly
      dist: xenial
    - python: pypy
      dist: trusty
  allow_failures:
    - python: nightly

before_install:
  - git submodule update --init --recursive
  - git clone --recursive git://github.com/maxmind/libmaxminddb
  - cd libmaxminddb
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - pip install -e git+https://github.com/maxmind/MaxMind-DB-Reader-python#egg=maxminddb
  - "if [[ $RUN_SNYK ]]; then sudo apt-get install -y nodejs; npm install -g snyk; fi"
install:
  - pip install -r requirements.txt
  - pip install requests_mock pylint coveralls yapf
  - "if [[ $RUN_SNYK ]]; then snyk test --org=maxmind; fi"
script:
  - coverage run --source=geoip2 setup.py test
  - "if [[ $RUN_LINTER ]]; then ./.travis-pylint.sh; fi"
  - "if [[ $RUN_LINTER ]]; then ./.travis-yapf.sh; fi"
after_success:
  - coveralls
  - "if [[ $RUN_SNYK && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then snyk monitor --org=maxmind --project-name=maxmind/GeoIP2-python; fi"
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "FZLn7HZnM6GOtIU7+W6tY6zd2y0K4C1ZgIOAiGscWvJydn+Xr63GCT21EPPe9QCulQHz88CWALMD7ZrDdsh6nV0gx0IeE+wq4w7NZYjLokvxs+UMYwuwl57MMrqd7e4byZDC4BLvTQTCvpOHOd8dCHwDXmuBcuyE8zB+Wkndn0I=\n"

env:
  global:
    secure: "YUqALSGB89cWyKNiBKIZDxdWPl3xjYjkWx2OP1i53W5qcaKgOWco2jv+2iXTPAk3c5x3Py3J7B1SdiNcRWmjfKqrnE47fZYkiP8rk0c/pVMRw0zURpmtRzSReDF0Sh/1ZTODi2rsU52Ei1f++BTEB5m409RMnTEvQtH7XT2sVDk="
